- hosts: localhost
  vars:
    node_version: "20.12.2"
    tmux_version: "3.4"
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    home_dir: "{{ lookup('env', 'HOME') }}"
    username: "{{ lookup('env', 'USER') | default('joqsan', true) }}"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core

  tasks:
    - import_tasks: tasks/nodejs.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-utils.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/productivity.yml
    - import_tasks: tasks/neovim.yml
    # - import_tasks: tasks/docker.yml