- name: Install core packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - ca-certificates
      - gcc
      - ninja-build
      - gettext
      - cmake
      - unzip
      - curl
      - git
      - python3
      - python-dev-is-python3
      - python3.10-venv
      - locales
      - nodejs
      - npm
      - ripgrep
  tags:
    - core