- name: Install core packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
      - git
      - wget
      - unzip
      - curl
      - ripgrep  # needed for telescope.nvim
      - fd-find  # needed for venv-selector.nvim
  tags:
    - core

- name: Get fdfind path
  command: which fdfind
  register: fdfind_path

- name: Setup fdfind symlink according to docs
  file:
    src: "{{ fdfind_path.stdout }}"
    dest: "/usr/local/bin/fd"
    state: link
  when: fdfind_path is succeeded