- name: Configure dotfiles
  tags: dotfiles
  block:
    - name: Install stow
      apt: name=stow

    - name: Cloning .dotfiles
      become_user: "{{ username }}"
      git:
        repo: 'git@github.com:Joqsan/.dotfiles.git'
        dest: "{{ home_dir }}/.dotfiles"
        recursive: yes
        key_file: "{{ dest_key }}"
        update: yes
        accept_hostkey: yes
        version: master
      
    - name: Stow dotfiles
      become_user: "{{ username }}"
      shell: cd {{ home_dir }}/.dotfiles && chmod +x ubuntu install && ./ubuntu