- name: Install stow
  apt: name=stow
  tags:
    - dotfiles
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:Joqsan/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && chmod +x ubuntu install && ./ubuntu
  tags:
    - dotfiles