- name: Configure dotfiles
  tags: dotfiles
  block:
    - name: Install stow
      become: true
      apt: name=stow

    - name: Clone .dotfiles
      git:
        repo: 'https://github.com/Joqsan/.dotfiles.git'
        dest: "{{ home_dir }}/.dotfiles"
        recursive: yes
        version: edit-gitmodules
      
    - name: Stow dotfiles
      shell: cd {{ home_dir }}/.dotfiles && chmod +x ubuntu install && ./ubuntu