- name: Configure git setup
  tags: git
  block:
    - name: Git personal setup email
      git_config:
        name: user.email
        scope: global
        value: "joqsan.a@gmail.com"

    - name: Git personal setup name
      git_config:
        name: user.name
        scope: global
        value: "Joqsan Azocar"

    - name: Git personal setup core editor
      git_config:
        name: core.editor
        scope: global
        value: "nvim"

    - name: Git personal setup merge tool
      git_config:
        name: merge.tool
        scope: global
        value: "nvim"

    - name: Git personal setup mergetool cmd
      git_config:
        name: mergetool.nvim.cmd
        scope: global
        value: 'nvim -d -c "wincmd l" -c "norm ]c" "$LOCAL" "$MERGED" "$REMOTE"'

    - name: Git personal setup mergetool keepBackup
      git_config:
        name: mergetool.keepBackup
        scope: global
        value: false

    - name: Git personal setup mergetool prompt
      git_config:
        name: mergetool.prompt
        scope: global
        value: false