- name: Setup node.js
  become: true
  tags: nodejs
  block:
    - name: Download node.js package
      get_url:
        url: http://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.gz
        dest: /opt

    - name: Uncompress the node.js package
      unarchive:
        src: /opt/node-v{{ node_version }}-linux-x64.tar.gz
        dest: /opt
        copy: no

    - name: Setup symlinks
      file:
        src: "/opt/node-v{{ node_version }}-linux-x64/bin/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        state: link
      with_items:
        - node
        - npm
        - npx