- name: Add productivity tools
  become: true
  tags: productivity
  block:
    - name: Install fzf
      become_user: "{{ username }}"
      shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

    - name: Install bat
      apt:
        name: bat
        state: present
    
    - name: Alias cat to batcat
      become_user: "{{ username }}"
      shell: echo 'alias cat=batcat' >> {{ home_dir }}/.aliases
