- name: Add productivity tools
  tags: productivity
  block:
    - name: Install fzf
      shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

    - name: Download tmux dependencies
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
          - libevent-dev
          - ncurses-dev
          - build-essential
          - bison
          - pkg-config

    - name: Download tmux latest version
      get_url:
        url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
        dest: /usr/local/bin/

    - name: Untar tmux
      command: tar -zxf tmux-{{ tmux_version }}.tar.gz
      args:
        chdir: /usr/local/bin/

    - name: Configure tmux
      shell: ./configure && make
      args:
        chdir: /usr/local/bin/tmux-{{ tmux_version }}

    - name: Make tmux
      shell: make install
      args:
        chdir: /usr/local/bin/tmux-{{ tmux_version }}
