- name: Add productivity tools
  tags: productivity
  block:
    - name: Install fzf
      shell: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install

    - name: Install tmux
      apt: name=tmux