- name: Install and configure zsh
  become: true
  tags: zsh
  block:
    - name: Install zsh
      apt: name=zsh

    - name: Change shell
      shell: chsh -s $(which zsh) {{ username }}

    - name: Install ohmyzsh
      become_user: "{{ username }}"
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
        creates: "{{ home_dir }}/.oh-my-zsh"
      
    - name: Download powerlevel10k theme
      become_user: "{{ username }}"
      shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git {{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k

    - name: Install the zsh plugin for autosuggestions
      become_user: "{{ username }}"
      git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

    - name: Check if .zshrc exists
      stat:
        path: "{{ home_dir }}/.zshrc"
      register: zsh_filepath

    - name: Remove .zshrc for stowing the correct one
      shell: "rm {{ home_dir }}/.zshrc"
      when: zsh_filepath.stat.exists == True
